POST http://localhost:3000/api/notes
content-type: application/json

{
  "content": "Mamma mia!",
  "important": true,
  "userId": "6745d50d64d026bbf4e59c00"
}

###
POST http://localhost:3000/api/notes
content-type: application/json

{
  "content": "BAZONGA"
}