POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyaWVuZGx5bWFuIiwiaWQiOiI2NzQ2NGU1MmIzZGFlZmY4OTZkOTM1N2QiLCJpYXQiOjE3MzI3Mzc2Njd9.TT5lr-93oQoYVd8_ZH1G81Jz-qo9dk2MB3OT72yLbmg

{
  "title": "How to unmake friend",
  "author": "NOT A FRIEND ANYMORE",
  "url": "howunmakefrend.com",
  "likes": 0
}